version: '3.7'

# Backend API
services:
  scrap-api:
    container_name: backend
    # image node: 12.14.0
    build: ./
    command: npm start
    working_dir: /usr/src/scrap-api
    environment: 
      POSTGRES_USER: david
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scrap-docker
      # POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/scrap-api
      
  # This is for running Postgres
  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: david
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scrap-docker
      # POSTGRES_HOST: postgres
    build: ./postgres
    # the build is referring to building what is in the postgres folder
    ports:
      - "5433:5432"
  
  # This is for running Redis
  redis:
    image: redis
    ports:
      - "6379:6379"